<?php

/**
 * @file
 * Code for the node_weight module.
 */

use Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException;
use Drupal\Component\Plugin\Exception\PluginNotFoundException;
use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityStorageException;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Utility\Error;
use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_help().
 */
function node_weight_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.node_weight') {
    $text = file_get_contents(__DIR__ . '/README.md');
    if (!Drupal::moduleHandler()->moduleExists('markdown')) {
      return '<pre>' . $text . '</pre>';
    }
    else {
      /** @var \Drupal\markdown\PluginManager\ParserManagerInterface $parser_manager */
      $parser_manager = \Drupal::service('plugin.manager.markdown.parser');
      $parser = $parser_manager->getDefaultParser([
        'render_strategy' => ['type' => 'none'],
      ]);
      return $parser->parse($text);
    }
  }
  return NULL;
}/**

  * Implements hook_preprocess_html().
  */
function node_weight_preprocess_html(&$variables) {
  $variables['#attached']['library'][] = 'node_weight/nodeweight';
}

/**
 * Implements hook_entity_operation().
 *
 * Creates 'Manage order' operation for content types at /admin/structure/types.
 */
function node_weight_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node_type' && \Drupal::currentUser()
    ->hasPermission('assign node weight')) {
    $operations['order'] = [
      'title' => t('Order Resources'),
      'weight' => 40,
      'url' => Url::fromRoute('node_weight.order', ['node_type' => $entity->id()]),
    ];
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function node_weight_menu_local_tasks_alter(&$data, $route_name, RefinableCacheableDependencyInterface &$cacheability) {
  // Get the node parameter from the current route.
  $node = \Drupal::routeMatch()->getParameter('node');

  // Check if $node is an object; if it's a string (node ID), load the entity.
  if (is_string($node)) {
    $node = \Drupal::entityTypeManager()->getStorage('node')->load($node);
  }

  // Ensure $node is an object before proceeding.
  if ($node && is_object($node)) {
    $allowed_types = ['resources_landing_page', 'resources'];
    $node_type = $node->bundle();

    // Only proceed if the node type is in the allowed list.
    if (in_array($node_type, $allowed_types)) {
      $nodetype = ['resources_landing_page', 'resources'];
      $url = Url::fromRoute('node_weight.order', ['node_type' => $nodetype]);
    }
  }
}

/**
 * Checks if node weight is enabled for given node type.
 *
 * @param string $node_type
 *   The node type id.
 *
 * @return bool
 *   TRUE if node weight is enabled for given node type, FALSE otherwise.
 */
function node_weight_node_type_enabled($node_type) {
  $config = \Drupal::config('node_weight.settings');
  $node_type_objects = $config->get('node_weight.checked_node_types') ?: [];
  if (array_search($node_type, array_values($node_type_objects), TRUE) !== FALSE) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Adds given node type to config.node_weight.checked_node_types.
 *
 * @param string $node_type
 *   The node type id.
 */
function node_weight_add_node_type_to_config($node_type) {
  $config = \Drupal::service('config.factory')
    ->getEditable('node_weight.settings');

  $node_type_objects = $config->get('node_weight.checked_node_types') ?: [];
  $node_type_objects[] = $node_type;

  $config->set('node_weight.checked_node_types', $node_type_objects);
  $config->save();
}

/**
 * Removes given node type from config.node_weight.checked_node_types.
 *
 * @param string $node_type
 *   The node type id.
 */
function node_weight_remove_node_type_from_config($node_type) {
  $config = \Drupal::service('config.factory')
    ->getEditable('node_weight.settings');

  $node_type_objects = $config->get('node_weight.checked_node_types') ?: [];
  unset($node_type_objects[array_search($node_type, $node_type_objects)]);

  $config->set('node_weight.checked_node_types', $node_type_objects);
  $config->save();
}

/**
 * Creates field_node_weight for given node_type.
 *
 * @param string $node_type
 *   The node type id.
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function node_weight_create_field_node_weight($node_type) {
  $field_storage = FieldStorageConfig::loadByName('node', 'field_node_weight');
  $field = FieldConfig::loadByName('node', $node_type, 'field_node_weight');

  if (empty($field)) {
    FieldConfig::create([
      'field_storage' => $field_storage,
      'field_name' => 'field_node_weight',
      'entity_type' => 'node',
      'bundle' => $node_type,
      'label' => t('Weight'),
      'type' => 'integer',
      'cardinality' => 1,
      'translatable' => TRUE,
      'default_value' => 0,
      'settings' => [
        'min' => -100,
        'max' => 100,
      ],
    ])->save();

    // Set field widget to weight_selector.
    \Drupal::entityTypeManager()
      ->getStorage('entity_form_display')
      ->load('node.' . $node_type . '.default')
      ->setComponent('field_node_weight', ['type' => 'weight_selector'])
      ->save();
  }
}

/**
 * Removes field field_node_weight from given node_type.
 *
 * @param string $node_type
 *   The node type id.
 */
function node_weight_delete_field_node_weight($node_type) {
  $field = FieldConfig::loadByName('node', $node_type, 'field_node_weight');
  if ($field) {
    $field->delete();
  }
}

/**
 * Implements hook_form_FORM_ID_form_alter().
 *
 * Adds options to the node_type_form for editing default node options.
 */
function node_weight_form_node_type_edit_form_alter(&$form, $form_state, $form_id) {
  $node_type = $form['type']['#default_value'];

  $form['weight_settings'] = node_weight_content_type_form_build($node_type);
  $form['actions']['submit']['#submit'][] = 'node_weight_form_node_type_add_form_submit';
}

/**
 * Additional submit handler function for node_type_form().
 */
function node_weight_form_node_type_edit_form_submit($form, &$form_state) {
  node_weight_content_type_form_submit($form['type']['#default_value'], $form_state->getValue('weight_enabled'));
}

/**
 * Implements hook_form_FORM_ID_form_alter().
 *
 * Adds weight settings form to details of the node_type_add_form.
 */
function node_weight_form_node_type_add_form_alter(&$form, $form_state, $form_id) {
  $node_type = $form['type']['#default_value'];

  $form['weight_settings'] = node_weight_content_type_form_build($node_type);
  $form['actions']['submit']['#submit'][] = 'node_weight_form_node_type_add_form_submit';
  $form['actions']['save_continue']['#submit'][] = 'node_weight_form_node_type_add_form_submit';
}

/**
 * Additional submit handler function for node_type_form().
 */
function node_weight_form_node_type_add_form_submit($form, &$form_state) {
  node_weight_content_type_form_submit($form_state->getValue(['type']), $form_state->getValue('weight_enabled'));
}

/**
 * Node Weight settings form.
 *
 * @params string $node_type
 *  The node type id.
 */
function node_weight_content_type_form_build($node_type): array {
  $available = node_weight_node_type_enabled($node_type);

  $form = [
    '#type' => 'details',
    '#title' => t('Node weight settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
    '#access' => \Drupal::currentUser()
      ->hasPermission('administer node weight'),
  ];

  $form['weight_enabled'] = [
    '#type' => 'radios',
    '#title' => t('Enable weight'),
    '#description' => t('Enable node weight for this content type?'),
    '#options' => [t('No'), t('Yes')],
    '#default_value' => ($available) ? 1 : 0,
  ];

  return $form;
}

/**
 * Node Weight content type form submit handler.
 *
 * @params string $node_type
 *     The node type id
 *
 * @params bool $weight_enabled
 *    TRUE if node_weight has to be enabled, FALSE otherwise
 */
function node_weight_content_type_form_submit($node_type, $weight_enabled) {
  if ($weight_enabled) {
    try {
      node_weight_create_field_node_weight($node_type);
    }
    catch (InvalidPluginDefinitionException | PluginNotFoundException | EntityStorageException $e) {
      $logger = \Drupal::logger('node_weight');
      Error::logException($logger, e);
    }

    if (!node_weight_node_type_enabled($node_type)) {
      node_weight_add_node_type_to_config($node_type);
    }
  }
  else {
    node_weight_delete_field_node_weight($node_type);

    if (node_weight_node_type_enabled($node_type)) {
      node_weight_remove_node_type_from_config($node_type);
    }
  }
}
