<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function olympian_private_webform_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['access']['create']['roles']['anonymous']['#disabled'] = TRUE;
  $form['access']['create']['roles']['anonymous']['#default_value'] = FALSE;
  $form['access']['configuration']['roles']['anonymous']['#disabled'] = TRUE;
  $form['access']['configuration']['roles']['anonymous']['#default_value'] = FALSE;
  $form['access']['view_any']['roles']['anonymous']['#disabled'] = TRUE;
  $form['access']['view_any']['roles']['anonymous']['#default_value'] = FALSE;
  $form['access']['update_any']['roles']['anonymous']['#disabled'] = TRUE;
  $form['access']['update_any']['roles']['anonymous']['#default_value'] = FALSE;
  $form['access']['purge_any']['roles']['anonymous']['#disabled'] = TRUE;
  $form['access']['purge_any']['roles']['anonymous']['#default_value'] = FALSE;
  $form['access']['view_own']['roles']['anonymous']['#disabled'] = TRUE;
  $form['access']['view_own']['roles']['anonymous']['#default_value'] = FALSE;
  $form['access']['update_own']['roles']['anonymous']['#disabled'] = TRUE;
  $form['access']['update_own']['roles']['anonymous']['#default_value'] = FALSE;
  $form['access']['delete_own']['roles']['anonymous']['#disabled'] = TRUE;
  $form['access']['delete_own']['roles']['anonymous']['#default_value'] = FALSE;
  $form['access']['administer']['roles']['anonymous']['#disabled'] = TRUE;
  $form['access']['administer']['roles']['anonymous']['#default_value'] = FALSE;
  $form['access']['test']['roles']['anonymous']['#disabled'] = TRUE;
  $form['access']['test']['roles']['anonymous']['#default_value'] = FALSE;
  unset($form['access']['create']['permissions']);
  unset($form['access']['configuration']['permissions']);
  unset($form['access']['view_any']['permissions']);
  unset($form['access']['update_any']['permissions']);
  unset($form['access']['delete_any']['permissions']);
  unset($form['access']['purge_any']['permissions']);
  unset($form['access']['view_own']['permissions']);
  unset($form['access']['update_own']['permissions']);
  unset($form['access']['delete_own']['permissions']);
  unset($form['access']['administer']['permissions']);
  unset($form['access']['test']['permissions']);

  if (strpos($form_id, 'webform_submission_') === 0) {
    $current_user = \Drupal::currentUser();
    
    // Redirect anonymous users.
    if ($current_user->isAnonymous()) {
      $form['#access'] = FALSE;
      \Drupal::messenger()->addWarning(t('You must be logged in to access this form.'));
    }
  }
}

/**
 * Implements hook_webform_access_rules_alter().
 */
function olympian_private_webform_webform_access_rules_alter(array &$access_rules) {
  if (isset($access_rules['create'])) {
    $access_rules['create']['roles'] = ['authenticated'];
  }
}
