<?php

/**
 * @file
 * Primary module hooks for johnmaxwulfing_core module.
 */
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function johnmaxwulfing_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_coin_form':
    case 'node_coin_edit_form':

      // Set form defaults if they exist.
      _olympian_node_form_defaults($form, $form_state);
      $form['field_coin_meta_tags']['widget'][0]['basic']['#open'] = FALSE;
      $form['field_coin_meta_tags']['widget'][0]['advanced']['#open'] = FALSE;

      break;
    }
  }
/**
 * Implements hook_preprocess_html().
 */
function johnmaxwulfing_core_preprocess_html(&$variables) {
  $variables['#attached']['library'][] = 'johnmaxwulfing_core/coin';
}

/**
 * Implements hook_theme().
 */
function johnmaxwulfing_core_theme($existing, $type, $theme, $path) {
  return [
    'node__coin_collection_landing_page' => [
      'template' => 'node--coin-collection-landing-page',
      'base hook' => 'node',
    ],
    'node__coin__teaser' => [
      'template' => 'node--coin--teaser',
      'base hook' => 'node',
    ],
    'node__coin' => [
      'template' => 'node--coin',
      'base hook' => 'node',
    ],
    'views_exposed_form__coin_collection_grid__2' => [
      'template' => 'views-exposed-form--coin-collection-grid--2',
      'base hook' => 'views_exposed_form',
    ],
  ];
}
