#!/bin/bash

## Description: Build the demo website
## Usage: build

# Install Composer dependencies.
composer install --prefer-dist

# Install Drupal from an installation profile.
drush site:install artsci --yes
drush updb --yes
drush cim --yes

yarn --cwd=/var/www/html/web/themes/custom/olympian9 run build
drush cr
drush uli
